FROM node:12-alpine as build-stage
RUN apk add git
WORKDIR /app

COPY frontend/package*.json ./

RUN yarn
COPY frontend/ .
# RUN rm /app/frontend/yarn.lock
RUN yarn build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
