# Generated by Django 3.0.11 on 2020-11-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_auto_20201123_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='donors.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='donors.Campaign'),
            preserve_default=False,
        ),
    ]
