# Generated by Django 3.0.11 on 2020-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_auto_20201123_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
