# Generated by Django 3.0.11 on 2020-11-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donor_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitals_ocupation_rate', models.IntegerField(default=0)),
                ('new_cases', models.IntegerField(default=0)),
                ('infection_rate', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='need',
            old_name='supplier',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='donor',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='expense',
            name='available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='in_use',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='need',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
