# Generated by Django 3.0.11 on 2020-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_auto_20201127_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
