# Generated by Django 3.0.11 on 2020-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_auto_20201127_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
