# Generated by Django 3.0.11 on 2020-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_auto_20201127_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_anonym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
