# Generated by Django 3.0.11 on 2020-11-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_auto_20201128_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(null=True, upload_to='logos'),
        ),
    ]
