# Generated by Django 3.0.11 on 2020-11-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0012_auto_20201128_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
