# Generated by Django 3.0.11 on 2020-11-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_partner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(default='project', max_length=30),
        ),
    ]
