# Generated by Django 3.0.11 on 2020-11-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_auto_20201128_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
